version: "3.9"

services:
  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: tonino-pizza
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_HOST_AUTH: trust
    ports:
      - 5432:5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data:
    driver: local
